name = "revasy"
pages_build_output_dir = ".open-next/assets"
compatibility_date = "2025-09-01"
compatibility_flags = ["nodejs_compat"]


[[d1_databases]]
binding = "DB"
database_name = "revasy-db"
database_id = "52df4dc3-0470-4abb-a41d-c1d9c534defc"

[ai]
binding = "AI"
